version: '3'
services:
  axigen:
    image: apandiyan/axigen:10.3.1-pc
    environment:
      - AXIGEN_PRECONFIGURED=yes
      - AXIGEN_ADMIN_PASSWORD=unknownadmin
    ports:
      - 9000:9000
      - 7000:7000
      - 21:21
      - 443:443
      - 465:465
      - 995:995
      - 993:993
    volumes:
      - axigen_data:/var/opt/axigen
      - ./axigen_lk.bin_secure:/var/opt/axigen/axigen_lk.bin:ro
      
volumes:
  axigen_data: