#!/bin/bash

## Build Arguments for pre-configured
BASE_IMAGE=centos:8.1.1911
AXIGEN_VERSION=10.3.1

## Bash variables
PRE_INSTALLED_TAG=apandiyan/axigen:$AXIGEN_VERSION
PRE_CONFIGURED_TAG=apandiyan/axigen:$AXIGEN_VERSION-pc
LATEST_TAG=apandiyan/axigen:latest


echo "=> Building pre-installed image with tag of version, latest"
docker build --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg AXIGEN_VERSION=$AXIGEN_VERSION -t $PRE_INSTALLED_TAG .
docker tag $PRE_INSTALLED_TAG $LATEST_TAG

echo "=> Building pre-configured image with tag of version with notation"
sudo docker build -t $PRE_CONFIGURED_TAG --build-arg AXIGEN_VERSION=$AXIGEN_VERSION --build-arg AXIGEN_PRECONFIGURE="yes" --build-arg AXIGEN_PRECONFIGURE_SMTPFILTERS="yes" .

echo "=> Building completed"
