#!/bin/bash

## Fetch Axigen version to install inside the image
AXIGEN_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f1)

if [ $(echo $DOCKER_TAG | cut -d "-" -f2) == "pc" ]; then
  docker build -t $IMAGE_NAME --build-arg AXIGEN_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f1) --build-arg AXIGEN_PRECONFIGURE="yes" --build-arg AXIGEN_PRECONFIGURE_SMTPFILTERS="yes" .
else
  docker build -t $IMAGE_NAME --build-arg AXIGEN_VERSION=$DOCKER_TAG .
fi
