#!/bin/bash

if [ $(echo $DOCKER_TAG | cut -d "-" -f2) != "pc" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
  docker tag $IMAGE_NAME $DOCKER_REPO:10.3.1.28
  docker push $DOCKER_REPO:10.3.1.28
else
  docker tag $IMAGE_NAME $DOCKER_REPO:10.3.1.28-pc
  docker push $DOCKER_REPO:10.3.1.28-pc
fi
